.TH "_Point" 3Version 1.0" "LCG_cg" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Point \- 3D point structure\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.ti -1c
.RI "double \fBz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
3D point structure\&. 
.PP
Definition at line \fB124\fP of file \fBtorus\&.cpp\fP\&.
.SH "Field Documentation"
.PP 
.SS "double _Point::x"

.PP
Definition at line \fB125\fP of file \fBtorus\&.cpp\fP\&.
.SS "double _Point::y"

.PP
Definition at line \fB125\fP of file \fBtorus\&.cpp\fP\&.
.SS "double _Point::z"

.PP
Definition at line \fB125\fP of file \fBtorus\&.cpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LCG_cg from the source code\&.
